import test from 'node:test';import assert from 'node:assert/strict';
import {generate,validate,grade,sequence,clone,progression,fingerprint} from '../web/domain.js';
import {schedule,render,Player,chooseInstrument} from '../web/audio.js';
import {fresh,validateBackup,mergeBackup} from '../web/store.js';
import {mergeProgress,syncProgress} from '../web/sync.js';
test('700 generated phrases fill exact bars and reproduce deterministic seeds',()=>{for(let level=0;level<7;level++)for(let seed=0;seed<100;seed++){const s=generate(seed,level,80,1+seed%4);assert.deepEqual(validate(s),[]);assert.deepEqual(s,generate(seed,level,80,1+seed%4));assert.equal(grade(s,s).integrated,1);}});
test('pitch errors leave rhythm evidence intact and rhythm errors leave pitch intact',()=>{const t=sequence([12,12,24],[28,29,30]),a=clone(t);a.events[1].step=32;assert.equal(grade(t,a).durations,1);assert.ok(grade(t,a).pitch<1);const b=sequence([24,12,12],[28,29,30]);assert.equal(grade(t,b).pitch,1);assert.ok(grade(t,b).durations<1);});
test('tie sustains one sound and unknown entry cannot pass',()=>{const t=sequence([24,24],[28,29]),a=sequence([12,12,24],[28,28,29]);a.events[0].tie=true;assert.equal(grade(t,a).integrated,1);assert.equal(schedule(a,'none').notes.length,2);a.events[2].step=null;assert.equal(grade(t,a).integrated,0);});
test('audio exact support timeline, finite PCM and no clipping',()=>{const s=sequence([24,24],[28,29],{bpm:120});assert.equal(schedule(s,'countin').notes[0].time,2);assert.equal(schedule(s,'none').notes[0].time,0);assert.equal(schedule(s,'subdivision').clicks.length,12);assert.ok(render({...s,instrument:'flute'}).every(x=>Number.isFinite(x)&&Math.abs(x)<=.951));});
test('malformed backup is rejected',()=>{const s=fresh();s.lessonPasses={0:'wrong'};assert.throws(()=>validateBackup(s));assert.throws(()=>validateBackup({...fresh(),resetAt:'tomorrow'}));});
test('progression requires distinct comparable independent examples',()=>{const a={target:generate(3),policy:{mode:'exam',support:'none',hearings:1},kind:'independent',assistance:[],audioOK:true,result:{complete:true,attacks:1,durations:1,pitch:1,integrated:1}};a.fingerprint=fingerprint(a.target);assert.equal(progression(Array(20).fill(a),a).action,'consolidate');});
test('sync merges lessons and reset generation defeats stale offline progress',()=>{const a={...fresh(),updatedAt:10,lesson:2},b={...fresh(),updatedAt:20,lesson:3};a.lessonPasses[1]=['a'];b.lessonPasses[1]=['b'];assert.deepEqual(mergeProgress(a,b).lessonPasses[1],['a','b']);assert.equal(mergeProgress(a,b).lesson,3);assert.equal(mergeProgress({...fresh(),resetAt:30},b).lesson,0);});
test('sync retries conflicts and requires private storage',async()=>{let puts=0;const request=async(url,opts)=>{if(!url.includes('/contents/'))return {ok:true,json:async()=>({private:true})};if(opts.method==='PUT')return ++puts===1?{ok:false,status:409}:{ok:true};return {ok:false,status:404};};assert.equal((await syncProgress(fresh(),{repo:'owner/private',token:'test'},request)).schema,1);assert.equal(puts,2);await assert.rejects(()=>syncProgress(fresh(),{repo:'owner/public',token:'test'},async()=>({ok:true,json:async()=>({private:false})})),/private/);});
test('stopping while audio unlock is pending cannot start sound',async()=>{let resolve,starts=0;const old=globalThis.AudioContext;globalThis.AudioContext=class{state='running';resume(){return new Promise(r=>resolve=r)}createBuffer(){return {copyToChannel(){}}}createBufferSource(){return {connect(){},start(){starts++}}}};try{const p=new Player(),pending=p.play(generate(1),'none');p.stop();resolve();await pending;assert.equal(starts,0);}finally{globalThis.AudioContext=old;}});

test('starting pitch and chord precede count-in without shifting relative rhythm',()=>{const s=sequence([12,12,24],[28,29,30],{bpm:120,reference:'chord'}),p=schedule(s,'countin');assert.deepEqual(p.referenceNotes.map(x=>x.midi),[60,64,67]);assert.equal(p.clicks[0].time,1.8);assert.equal(p.notes[0].time,3.8);assert.equal(p.notes[1].time-p.notes[0].time,.5);assert.equal(schedule({...s,reference:'first'},'none').referenceNotes[0].midi,60);});
test('mixed instruments never immediately repeat and fixed piano stays piano',()=>{for(const instrument of ['piano','flute','clarinet'])for(const r of [0,.5,.999])assert.notEqual(chooseInstrument('mixed',instrument,()=>r),instrument);assert.equal(chooseInstrument('piano','piano'),'piano');});
test('bundled piano samples render finite distinct audio with a chord',async()=>{const {readFile}=await import('node:fs/promises');const piano={};for(const root of [48,54,60,66,72,78,84,90,96]){const data=await readFile(new URL('../web/piano/'+root+'.pcm',import.meta.url));piano[root]=Float32Array.from(new Int16Array(data.buffer,data.byteOffset,data.byteLength/2),x=>x/32768);}const score=sequence([12,12,24],[28,29,30],{reference:'chord'}),pcm=render(score,'none',22050,piano);assert.ok(pcm.some(x=>Math.abs(x)>.01));assert.ok(pcm.every(x=>Number.isFinite(x)&&Math.abs(x)<=.951));assert.notDeepEqual(pcm,render({...score,instrument:'flute'},'none',22050));assert.notDeepEqual(render({...score,instrument:'flute'},'none',22050),render({...score,instrument:'clarinet'},'none',22050));});
