import test from 'node:test';import assert from 'node:assert/strict';
import {KEYS,METERS,SCALES,generate,validateScore,validate,barTicks,meterInfo,midi,keyAcc,sequence,comparable} from '../web/domain.js';
import {schedule} from '../web/audio.js';import {staffSVG} from '../web/staff.js';import {LESSONS} from '../web/lessons.js';
test('189 key spellings reproduce their interval collections including double accidentals',()=>{assert.equal(Object.keys(KEYS).length,189);for(const [key,k] of Object.entries(KEYS)){const notes=SCALES[k.scale].map((_,i)=>({step:k.tonic+i,acc:keyAcc({key},k.tonic+i),rest:false}));assert.deepEqual(notes.map(n=>midi(n)-k.chord[0]),SCALES[k.scale]);assert.ok(notes.every(n=>Math.abs(n.acc)<=2));}assert.equal(keyAcc({key:'G# harmonic minor'},38),2);assert.equal(keyAcc({key:'Cb minor'},30),-2);});
test('all 30,240 key and meter combinations generate valid scores and exact bar lengths',()=>{assert.equal(METERS.length,160);let i=0;for(const key of Object.keys(KEYS))for(const meter of METERS){const s=generate(i++,6,80,1,{key,meter});assert.deepEqual(validate(s),[]);assert.doesNotThrow(()=>validateScore(s));assert.equal(s.events.reduce((n,e)=>n+e.duration,0),barTicks(s));}});
test('every meter at every level stays representable across four bars',()=>{for(const meter of METERS)for(let level=0;level<7;level++){const s=generate(2026,level,80,4,{meter,key:'B# harmonic minor'});assert.deepEqual(validate(s),[]);assert.doesNotThrow(()=>validateScore(s));}});
test('unequal 7/8 pulses and count-in follow actual 2+2+3 lengths',()=>{const s=sequence([6,6,6,6,6,6,6],[28,29,30,28,29,30,28],{meter:'7/8',grouping:'2+2+3',bpm:120});const p=schedule(s,'beat');assert.deepEqual(p.clicks.map(x=>x.time),[0,1,2,3.5,4.5,5.5]);assert.equal(p.notes[0].time,3.5);assert.equal(p.length,7.15);const reverse=schedule({...s,grouping:'3+2+2'},'beat');assert.deepEqual(reverse.clicks.slice(0,3).map(x=>x.time),[0,1.5,2.5]);assert.equal(schedule(s,'subdivision').clicks.length,10);});
test('compound and cut-time tempos use explicit units without fractional-tick drift',()=>{assert.equal(meterInfo({meter:'9/8'}).unit,18);assert.equal(meterInfo({meter:'12/16'}).unit,9);assert.equal(meterInfo({meter:'2/2'}).unit,24);assert.equal(meterInfo({meter:'3/2'}).unit,24);const p=schedule(generate(1,0,120,1,{meter:'2/2'}),'beat');assert.equal(p.length,2.15);});
test('groupings are validated, rendered and isolated in comparison evidence',()=>{for(const grouping of ['2+2','0+7','-1+8','2+2+3<script>','3.5+3.5'])assert.throws(()=>meterInfo({meter:'7/8',grouping}));const target=generate(4,6,80,1,{meter:'7/8',key:'G# harmonic minor',grouping:'2+2+3'});const a={target,policy:{}};assert.notEqual(comparable(a),comparable({...a,target:{...target,grouping:'3+2+2'}}));assert.match(staffSVG(target,{grid:true}),/7\/8/);const ds=sequence([12],[38],{key:'G# harmonic minor'});ds.events[0].acc=2;assert.match(staffSVG(ds),/𝄪/);});
test('every lesson has a complete meter and valid key spelling',()=>{assert.equal(LESSONS.length,18);for(const l of LESSONS){const s=sequence(l.durations,l.steps,{key:l.key||'C major',meter:l.meter||'4/4',grouping:l.grouping});s.events.forEach(e=>{if(!e.rest)e.acc=keyAcc(s,e.step);});assert.deepEqual(validate(s),[]);assert.doesNotThrow(()=>validateScore(s));}});

test('expanded range cannot masquerade as the earlier five-note conditions',()=>{const target=generate(1,6);const legacy={...target};delete legacy.pitchRange;assert.notEqual(comparable({target,policy:{}}),comparable({target:legacy,policy:{}}));});
