import test from 'node:test';import assert from 'node:assert/strict';
import {KEYS,METERS,generate,validate,barTicks,grade,sequence,comparable,clone} from '../web/domain.js';
import {schedule} from '../web/audio.js';import {reviewPlan,comparisons,REVIEW_DELAYS,draftEvidence} from '../web/review.js';import {fresh,validateBackup,mergeBackup,save,read,KEY} from '../web/store.js';
test('all keys and meters: 5600 deterministic, correctly filled phrases',()=>{for(const key of ['C major','G major','F major','A minor'])for(const meter of ['2/4','3/4','4/4','6/8'])for(let level=0;level<7;level++)for(let seed=0;seed<50;seed++){const s=generate(seed,level,80,1+seed%4,{key,meter});assert.deepEqual(validate(s),[]);assert.equal(s.events.reduce((a,e)=>a+e.duration,0),s.bars*barTicks(s));assert.ok(s.events.every(e=>e.rest||e.step>=28&&e.step<=41));}});
test('compound meter uses dotted-quarter tempo, three subdivisions and a two-beat count-in',()=>{const s=sequence([6,6,6,18],[28,29,30,28],{meter:'6/8',bpm:120});const a=schedule(s,'subdivision');assert.equal(a.notes[0].time,1);assert.equal(a.notes[1].time,1+1/6);assert.equal(a.notes[3].duration,.5);assert.equal(a.clicks.length,8);assert.equal(a.length,2.15);});
test('minor and transposed references use the correct actual pitches',()=>{for(const [key,chord] of [['G major',[67,71,74]],['F major',[65,69,72]],['A minor',[69,72,76]]]){const s=generate(2,2,80,1,{key});s.reference='chord';assert.deepEqual(schedule(s).referenceNotes.map(n=>n.midi),chord);}});
test('meter and tonality partition comparisons; changed rhythm retains pitch credit',()=>{const a={target:generate(1),policy:{mode:'exam',support:'none',hearings:2}},b=clone(a);b.target.key='A minor';assert.notEqual(comparable(a),comparable(b));const t=sequence([12,12,12],[28,29,30],{meter:'3/4'}),answer=sequence([6,18,12],[28,29,30],{meter:'3/4'});assert.equal(grade(t,answer).pitch,1);assert.ok(grade(t,answer).durations<1);});
function attempt(id,created,score=1){const target=sequence([12,12,24],[28,29,30]);target.events[0].acc=id%2;target.events[1].acc=Math.floor(id/2)%2;target.events[2].acc=Math.floor(id/4)%2;return {id:String(id),created,target,answer:clone(target.events),policy:{mode:'exam',support:'none',hearings:2,rhythmOnly:false},assistance:[],kind:'independent',audioOK:true,completed:1,exposures:1,submitted:true,drafts:[],result:{complete:true,integrated:score,attacks:score,durations:score,pitch:1}};}
test('retention requires delayed unfamiliar success; immediate repeats never qualify',()=>{const t=1000,a=attempt(0,t),b=attempt(1,t+REVIEW_DELAYS[0]),c=attempt(2,b.created+REVIEW_DELAYS[1]);assert.equal(reviewPlan([a],t)[0].stage,0);assert.equal(reviewPlan([a,b],b.created)[0].stage,1);assert.equal(reviewPlan([a,b,c],c.created)[0].stage,2);assert.equal(reviewPlan([a,attempt(1,t+100),attempt(2,t+200)],t+300)[0].stage,0);assert.equal(reviewPlan([a,{...a,id:'duplicate',created:t+1e9}],t+1e9)[0].count,1);assert.equal(reviewPlan([a,b,c,attempt(3,c.created+100,.5)])[0].status,'Needs review');});
test('matched comparisons do not overlap or include assisted work',()=>{const rows=Array.from({length:8},(_,i)=>attempt(i,i*1000,i<4?.5:1));assert.equal(comparisons(rows.slice(0,7))[0].baseline,null);const c=comparisons(rows)[0];assert.equal(c.baseline.rhythm,.5);assert.equal(c.recent.rhythm,1);rows[7].assistance=['answer playback'];assert.equal(comparisons(rows)[0].baseline,null);});
test('backups do not mutate caller data, and imported live drafts cannot earn independent evidence',()=>{const s=fresh();s.session=attempt(0,1000);s.session.submitted=false;s.session.result=null;const original=clone(s);validateBackup(s);assert.deepEqual(s,original);assert.ok(mergeBackup(fresh(),s).session.assistance.includes('imported draft'));const bad=clone(s);bad.profile.volume=8;assert.throws(()=>validateBackup(bad));});
test('previous save recovery survives a changed draft',()=>{const map=new Map(),storage={getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};const state=fresh();save(storage,state);state.lesson=2;save(storage,state);assert.equal(read(storage).lesson,2);assert.equal(JSON.parse(storage.getItem(KEY+'.previous')).lesson,0);});
test('draft feedback retains first-hearing incompleteness',()=>{const a=attempt(1,1000);a.drafts=[{hearing:1,elapsed:1000,answer:[]},{hearing:2,elapsed:2000,answer:a.answer}];const d=draftEvidence(a);assert.equal(d[0].result.integrated,0);assert.equal(d[1].result.integrated,1);});
