import {test,expect} from '@playwright/test';
const key='theory-dictation-master.web.v1';
test.beforeEach(async({page})=>{await page.addInitScript(()=>{window.audioStarts=0;if(!globalThis.AudioBufferSourceNode)return;const original=AudioBufferSourceNode.prototype.start;AudioBufferSourceNode.prototype.start=function(...args){window.audioStarts++;return original.apply(this,args);};});await page.goto('/');});
test('silent editing, persistence, real explicit audio, assessment and reset',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.locator('[data-page="practice"]').click();await expect(page.locator('#score svg')).toBeVisible();await expect(page.locator('#target-tab')).toBeHidden();
 await page.locator('[data-pitch="28"]').click();await page.locator('[data-pitch="29"]').click();await page.locator('#pitch-up').click();await page.locator('#duration').selectOption('6');await page.locator('#apply').click();await page.locator('#tie').click();await page.locator('#undo').click();await page.locator('#redo').click();await page.locator('#delete').click();
 expect(await page.evaluate(()=>window.audioStarts)).toBe(0);await page.reload();await expect(page.locator('#score [data-note]')).toHaveCount(1);expect(await page.evaluate(()=>window.audioStarts)).toBe(0);
 await page.locator('.setup summary').click();await page.locator('#bpm').fill('160');await page.locator('#support').selectOption('none');await page.locator('#mode').selectOption('exam');await page.locator('#next').click();await expect(page.locator('#play-answer')).toBeDisabled();await expect(page.locator('#depitch')).toBeDisabled();await expect(page.locator('#target-tab')).toBeHidden();await page.locator('#hear').click();await expect(page.locator('#save-draft')).toBeEnabled({timeout:10000});expect(await page.evaluate(()=>window.audioStarts)).toBe(1);await expect(page.locator('#hear')).toBeDisabled();await page.locator('#save-draft').click();await expect(page.locator('#hear')).toBeEnabled();await page.locator('#submit').click();await expect(page.locator('#scores')).toContainText('Integrated');await expect(page.locator('#target-tab')).toBeVisible();
 await page.locator('[data-page="settings"]').click();page.once('dialog',d=>d.accept());await page.locator('#reset-progress').click();const state=await page.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);expect(state.attempts).toHaveLength(0);expect(state.earnedLevel).toBe(0);expect(state.session.answer).toHaveLength(0);expect(errors).toEqual([]);
});
test('lesson, paper mode, mobile layout and offline reload',async({page,context})=>{await page.locator('[data-page="learn"]').click();await expect(page.locator('#lesson-score svg')).toBeVisible();await page.locator('#lesson-guided').click();await expect(page.locator('#target-tab')).toBeVisible();await page.locator('.setup summary').click();await page.locator('#mode').selectOption('paper');await page.locator('#next').click();await expect(page.locator('#paper-prompt')).toBeVisible();await expect(page.locator('#score')).toBeHidden();await page.locator('#enter-paper').click();await page.locator('[data-pitch="30"]').click();expect(await page.evaluate(()=>window.audioStarts)).toBe(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.evaluate(()=>navigator.serviceWorker.ready);await page.reload();await context.setOffline(true);await page.reload();await expect(page.locator('#score [data-note]')).toHaveCount(1);await context.setOffline(false);});
test('sync UI transfers progress through GitHub API and never saves token',async({page})=>{let file=null,sha=0;await page.route('https://api.github.com/repos/**',async route=>{const headers={'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'GET, PUT, OPTIONS'};if(route.request().method()==='OPTIONS')return route.fulfill({status:204,headers});if(!route.request().url().includes('/contents/'))return route.fulfill({headers,json:{private:true}});if(route.request().method()==='PUT'){file=route.request().postDataJSON().content;sha++;return route.fulfill({headers,json:{content:{sha:String(sha)}}});}return file?route.fulfill({headers,json:{sha:String(sha),content:file,size:file.length}}):route.fulfill({status:404,headers,json:{message:'not found'}});});await page.locator('[data-page="settings"]').click();await page.locator('#sync-token').fill('test-only-token');await page.locator('#sync-now').click();await expect(page.locator('#sync-status')).toContainText('Synced successfully');expect(file).toBeTruthy();expect(await page.evaluate(()=>JSON.stringify(localStorage))).not.toContain('test-only-token');await page.locator('#disconnect-sync').click();await expect(page.locator('#sync-token')).toHaveValue('');});
