import {test,expect} from '@playwright/test';
const KEY='theory-dictation-master.web.v1';
test('compound meter, key spelling, new lessons and saved preset',async({page})=>{
 await page.goto('./');await page.locator('[data-page="practice"]').click();await page.locator('.setup summary').click();await page.locator('#key').selectOption('F major');await page.locator('#meter').selectOption('6/8');await page.locator('#next').click();await expect(page.locator('#phrase-context')).toContainText('F major');await expect(page.locator('#phrase-context')).toContainText('6/8');await page.locator('[data-pitch="34"]').click();expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).session.answer[0].acc,KEY)).toBe(-1);await expect(page.locator('#score .score-context')).toContainText('F major');await expect(page.locator('#score .score-context')).toContainText('6/8');await expect(page.locator('#score')).toContainText('♭');
 await page.locator('[data-page="settings"]').click();await page.locator('#save-preset').click();await page.reload();await page.locator('#load-preset').click();await expect(page.locator('#phrase-context')).toContainText('6/8');await page.locator('[data-page="learn"]').click();await page.locator('#lesson-select').selectOption('12');await expect(page.locator('#lesson-title')).toContainText('6/8');await page.locator('#lesson-guided').click();await expect(page.locator('#phrase-context')).toContainText('6/8');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
test('another tab cannot overwrite a newer draft',async({page,context})=>{
 await page.goto('./#practice');const second=await context.newPage();await second.goto('./#practice');await second.locator('[data-pitch="28"]').click();await expect(page.locator('#tab-conflict')).toBeVisible();await page.locator('#reload-progress').click();await expect(page.locator('#score [data-note]')).toHaveCount(1);
});
test('corrupt current record recovers previous save without losing it',async({page})=>{
 await page.goto('./#practice');await page.locator('[data-pitch="28"]').click();await page.addInitScript(k=>{localStorage.setItem(k+'.previous',localStorage.getItem(k));localStorage.setItem(k,'broken-json');},KEY);await page.reload();await expect(page.locator('#score [data-note]')).toHaveCount(1);expect(await page.evaluate(k=>localStorage.getItem(k+'.recovery'),KEY)).toBe('broken-json');
});
test('legacy saved progress survives the upgrade and can be inspected',async({page})=>{
 await page.goto('./#practice');await page.locator('[data-pitch="28"]').click();await page.locator('#next').click();await page.addInitScript(k=>{const data=JSON.parse(localStorage.getItem(k));data.version='0.2.1';delete data.session.target.key;for(const a of data.attempts)delete a.target.key;localStorage.setItem(k,JSON.stringify(data));},KEY);await page.reload();await page.locator('[data-page="progress"]').click();await page.getByRole('button',{name:'Inspect',exact:true}).first().click();await expect(page.locator('#attempt-detail')).toContainText('Saved attempt');expect(await page.evaluate(k=>JSON.parse(localStorage.getItem(k)).attempts.length,KEY)).toBe(1);
});
