import {reviewPlan,comparisons,draftEvidence} from './review.js';
import {syncProgress} from './sync.js';
import {VERSION,Q,LEVELS,DURATIONS,clone,generate,sequence,reflow,grade,name,validate,fingerprint,independent,progression,barTicks,beatTicks,KEYS,keyAcc,keyInfo,METERS,SCALES,meterInfo,tempoLabel} from './domain.js';
import {read,save,fresh,mergeBackup,KEY,validateBackup} from './store.js';
import {Player,wav,chooseInstrument} from './audio.js';
import {staffSVG,stepFor} from './staff.js';
import {LESSONS} from './lessons.js';
const $=id=>document.getElementById(id),player=new Player();let state,session,selected=-1,undo=[],redo=[],targetView=false,paperEntry=false,page='today',busy=false,playKind=null,noticeTimer,insert=false,blockEnd=null,recovery=null;
const SUPPORT={beat:'Beat clicks',subdivision:'Subdivision clicks',dropout:'Dropout',countin:'Count-in only',none:'No clicks'};
const pct=x=>x===null?'Not assessed':Math.round(x*100)+'%';
function notice(text){$('notice').textContent=text;$('notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('notice').hidden=true,10000);}
for(const scale of Object.keys(SCALES)){const group=document.createElement('optgroup');group.label=scale==='minor'?'Natural minor':scale==='melodic minor'?'Melodic minor (raised 6/7 both directions)':scale;for(const key of Object.keys(KEYS).filter(k=>KEYS[k].scale===scale)){const option=document.createElement('option');option.value=key;option.textContent=key;group.append(option);}$('key').append(group);}
for(const meter of [...new Set(['4/4','2/4','3/4','6/8','9/8','12/8','5/8','7/8','5/4','7/4',...METERS])]){const option=document.createElement('option');option.value=option.textContent=meter;$('meter').append(option);}
$('key').value='C major';$('meter').value='4/4';
function updateMeterHelp(){try{const m=meterInfo({meter:$('meter').value,grouping:$('grouping').value.replace(/\s/g,'')});$('meter-help').textContent=`Groups: ${m.grouping}. Tempo: ${m.label.toLowerCase()} = ${$('bpm').value} BPM. Count-in follows these group lengths. Unequal groups use the denominator note as the tempo unit.`;}catch(e){$('meter-help').textContent=e.message;}}
for(const id of ['meter','grouping','bpm'])$(id).addEventListener('input',updateMeterHelp);updateMeterHelp();
try{state=read(localStorage);}catch{state=fresh();try{recovery=localStorage.getItem(KEY);localStorage.setItem(KEY+'.recovery',recovery);const previous=localStorage.getItem(KEY+'.previous');if(previous)state=validateBackup(JSON.parse(previous));localStorage.removeItem(KEY);notice(previous?'Recovered the previous save. The unreadable record is available in Settings.':'Saved data could not be opened. Export the recovery copy in Settings.');}catch{notice('Saved data could not be opened. Export a recovery copy in Settings.');}}

let staleTab=false;
function persist(){if(staleTab)return;state.version=VERSION;state.session=session??null;try{save(localStorage,state);}catch{notice('Your browser could not save progress. Export a backup before closing this page.');}}
function on(id,event,fn){$(id).addEventListener(event,async e=>{try{await fn(e);}catch(error){notice(error.message||String(error));}});}
function download(blob,filename){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
function settingValues(){for(const [id,min,max] of [['bpm',40,160],['bars',1,4],['hearings',1,20]])if(!Number.isInteger(+$(id).value)||+$(id).value<min||+$(id).value>max)throw Error(`${id} must be a whole number from ${min} to ${max}.`);return {level:+$('level').value,bpm:+$('bpm').value,bars:+$('bars').value,key:$('key').value,meter:$('meter').value,grouping:$('grouping').value.replace(/\s/g,''),instrument:$('instrument').value,reference:$('reference').value,policy:{mode:$('mode').value,support:$('support').value,hearings:+$('hearings').value,rhythmOnly:$('rhythm-only').checked}};}
function applySetup(){const t=session.target,p=session.policy;$('key').value=t.key||'C major';$('meter').value=t.meter||'4/4';$('grouping').value=t.grouping||'';$('instrument').value=t.soundMode||t.instrument||'piano';$('reference').value=t.reference||'none';$('level').value=t.level;$('bpm').value=t.bpm;$('bars').value=t.bars;$('mode').value=p.mode;$('support').value=p.support;$('hearings').value=p.hearings;$('rhythm-only').checked=p.rhythmOnly;updateMeterHelp();}
function newSession(target=null,assistance=[],lesson=null){
 const setup=settingValues();meterInfo(setup);stop();if(session&&!session.submitted&&(session.answer.length||session.exposures))record('abandoned');
 if(!target){const seen=new Set(state.attempts.map(a=>a.fingerprint));for(let i=0;i<300;i++){target=generate(crypto.getRandomValues(new Uint32Array(1))[0],setup.level,setup.bpm,setup.bars,{key:setup.key,meter:setup.meter,grouping:setup.grouping});if(!seen.has(fingerprint(target)))break;}if(seen.has(fingerprint(target)))assistance.push('familiar example; vocabulary pool exhausted');}
 target={...target,instrument:chooseInstrument(setup.instrument,session?.target.instrument),soundMode:setup.instrument,reference:setup.reference};state.updatedAt=Date.now();session={id:crypto.randomUUID(),created:Date.now(),target,answer:[],policy:setup.policy,assistance,exposures:0,completed:0,drafts:[],awaitingDraft:false,submitted:false,audioOK:true,playing:false,result:null,lesson,confidence:'Optional'};
 selected=-1;undo=[];redo=[];targetView=false;paperEntry=false;insert=false;$('confidence').value='Optional';persist();renderPractice();
}
function record(kind){if(state.attempts.length>=2000)throw Error('History is full. Export a backup in Settings before resetting.');state.updatedAt=Date.now();const a={...clone(session),kind,fingerprint:fingerprint(session.target)};if(!state.attempts.some(x=>x.id===a.id))state.attempts.push(a);return a;}
function navigate(next){
 stop();if(next==='learn'&&session&&!session.submitted&&session.exposures)assist('lesson visited during attempt');
 page=['today','learn','practice','progress','settings'].includes(next)?next:'today';document.querySelectorAll('.page').forEach(x=>x.hidden=x.id!==page);document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.page===page);b.setAttribute('aria-current',b.dataset.page===page?'page':'false');});
 history.replaceState(null,'','#'+page);if(page==='today')renderToday();if(page==='learn')renderLesson();if(page==='practice')renderPractice();if(page==='progress')renderProgress();if(page==='settings'){player.volume=state.profile.volume??.7;renderSettings();}window.scrollTo({top:0,behavior:'instant'});persist();
}
function renderToday(){const plans=reviewPlan(state.attempts),due=plans.filter(p=>p.isDue);$('review-reason').textContent=due.length?`${due.length} review group(s) due. ${due[0].reason}`:plans.length?`Next review: ${new Date(plans[0].due).toLocaleString()}. You can practice earlier without claiming delayed retention.`:'Complete an independent phrase to establish your first review.';$('start-review').disabled=!plans.length;const count=state.attempts.filter(independent).length;$('current-target').textContent=LEVELS[state.earnedLevel];$('home-evidence').innerHTML=`<span><strong>${state.attempts.length}</strong>saved attempts</span><span><strong>${count}</strong>complete independent attempts</span><span>Vocal rest ${state.profile.vocalRest?'on':'off'}</span>`;}
function showStaff(){const refocus=$('score').contains(document.activeElement);const paper=session.policy.mode==='paper'&&!session.submitted&&!paperEntry;const events=targetView?session.target.events:session.answer;$('score').hidden=paper;$('paper-prompt').hidden=!paper;$('editor-tools').hidden=paper||targetView;$('entry-controls').hidden=paper||targetView;$('score').innerHTML=staffSVG({...session.target,events},{selected,grid:session.policy.mode==='practice'&&$('grid').checked,readonly:session.submitted||targetView,title:targetView?'Target after submission':'Your transcription'});$('answer-tab').setAttribute('aria-selected',String(!targetView));$('target-tab').setAttribute('aria-selected',String(targetView));$('target-tab').hidden=!session.submitted&&!session.assistance.includes('worked example');$('entry-status').textContent=`Your entry: ${session.answer.reduce((s,e)=>s+(e.duration??0),0)/Q} / ${session.target.bars*barTicks(session.target)/Q} quarter-note units.${selected>=0&&session.answer[selected]?' Selected: '+name(session.answer[selected])+', '+(session.answer[selected].duration===null?'duration ?':session.answer[selected].duration/Q+' quarter-note units')+'.':''}`;
 if(refocus)$('score').querySelector('svg')?.focus({preventScroll:true});$('undo').disabled=session.submitted||!undo.length;$('redo').disabled=session.submitted||!redo.length;for(const id of ['apply','tie','delete','pitch-up','pitch-down'])$(id).disabled=session.submitted||selected<0;$('insert').disabled=session.submitted;$('insert').setAttribute('aria-pressed',String(insert));document.querySelectorAll('[data-pitch]').forEach(b=>b.disabled=session.submitted||targetView);
}
function renderPractice(){if(!session)return;document.querySelectorAll('[data-pitch]').forEach(b=>b.textContent=name({step:+b.dataset.pitch,acc:keyAcc(session.target,+b.dataset.pitch),rest:false}));const p=session.policy,t=session.target;
 $('phrase-context').textContent=`${t.key||'C major'} · ${t.meter} [${meterInfo(t).grouping}] · ${t.bars} bar${t.bars>1?'s':''} · ${tempoLabel(t)} = ${t.bpm} · ${SUPPORT[p.support]} · ${t.instrument||'piano'} · ${t.reference==='chord'?((t.key||'C major')==='C major'?'C-major chord':(t.key+' tonic chord')):t.reference==='pitch'?'Tonic reference':t.reference==='first'?'Starting-note reference':'No starting reference'} · ${p.mode==='exam'?'Assessment':p.mode==='paper'?'Paper':'Practice'}`;
 $('setup-summary').textContent=LEVELS[t.level];$('grid').disabled=p.mode!=='practice';if(p.mode!=='practice')$('grid').checked=false;
 $('hearing-count').textContent=`${session.exposures} / ${p.hearings} hearings`;
 $('coach-title').textContent=session.submitted?'Listen to the difference.':session.awaitingDraft?'Write what you retained.':'Listen for the whole.';
 $('coach-copy').textContent=session.submitted?'Compare the sound and notation. A targeted follow-up reconnects a difficult rhythm to changing pitches.':session.awaitingDraft?'Take your time. Mark rhythm, contour or any pitch landmark you caught, then save this hearing draft.':'Establish pulse and key. Hear the whole phrase, keep following it, and capture what you recognize in any order.';
 $('hear').disabled=busy||(!session.submitted&&(session.awaitingDraft||session.exposures>=p.hearings));$('hear').textContent=session.submitted?'Replay target':'Hear phrase';$('submit').disabled=session.submitted||busy||session.completed===0;$('save-draft').disabled=session.submitted||busy||!session.awaitingDraft;
 $('depitch').disabled=busy||(p.mode!=='practice'&&!session.submitted);$('play-answer').disabled=busy||!session.answer.length||(p.mode!=='practice'&&!session.submitted);$('tonic').disabled=busy;$('stop').disabled=!busy;
 $('print-key').hidden=!session.submitted;$('confidence').disabled=session.submitted;$('feedback-card').hidden=!session.submitted;
 showStaff();if(session.submitted)renderFeedback();else $('submission-comparison').replaceChildren();
}
function checkpoint(){undo.push(clone(session.answer));undo=undo.slice(-100);redo=[];}
function edited(){state.updatedAt=Date.now();session.answer=reflow(session.answer);persist();showStaff();$('play-answer').disabled=!session.answer.length||(session.policy.mode!=='practice'&&!session.submitted);}
function chosen(){const base=$('duration').value==='unknown'?null:+$('duration').value;return {duration:base===null?null:base*($('dot').checked?1.5:1),acc:$('accidental').value==='key'?null:+$('accidental').value,rest:$('rest').checked,unknown:$('unknown').checked};}
function add(step){if(staleTab)return;if(session.submitted||targetView||busy)return;const choice=chosen();if(choice.duration!==null&&!Number.isInteger(choice.duration)){notice('A dotted sixteenth is outside this release’s timing vocabulary. Choose an undotted sixteenth or dotted eighth.');return;}if(session.answer.length>=2048){notice('This phrase has reached the 2048-event limit.');return;}checkpoint();const e={onset:0,duration:choice.duration,step:choice.rest||choice.unknown?null:step,acc:choice.acc??keyAcc(session.target,step),rest:choice.rest,tie:false};const index=insert&&selected>=0?selected:session.answer.length;session.answer.splice(index,0,e);selected=index;edited();}
function edit(change){if(staleTab)return;if(session.submitted||targetView||selected<0||!session.answer[selected]||busy)return;checkpoint();if(change.step!==undefined&&$('accidental').value==='key')change.acc=keyAcc(session.target,change.step);Object.assign(session.answer[selected],change);edited();}
function remove(){if(session.submitted||selected<0||busy)return;checkpoint();session.answer.splice(selected,1);selected=Math.min(selected,session.answer.length-1);edited();}
function doUndo(){if(session.submitted||!undo.length||busy)return;redo.push(clone(session.answer));session.answer=undo.pop();selected=Math.min(selected,session.answer.length-1);state.tutorialDone=true;edited();}
function doRedo(){if(session.submitted||!redo.length||busy)return;undo.push(clone(session.answer));session.answer=redo.pop();selected=Math.min(selected,session.answer.length-1);edited();}
function assist(reason){if(!session.submitted&&!session.assistance.includes(reason))session.assistance.push(reason);persist();}
function stop(){if(busy&&playKind==='target'&&session&&!session.submitted){assist('interrupted playback');session.awaitingDraft=true;}player.stop();busy=false;playKind=null;if(session){session.playing=false;persist();if(page==='practice')renderPractice();}}
async function play(score,support,kind){
 if(busy)return;busy=true;playKind=kind;session.playing=kind==='target';state.updatedAt=Date.now();if(kind==='target')session.exposures++;persist();renderPractice();
 try{await player.play(score,support,()=>{busy=false;playKind=null;if(kind==='target'){session.completed++;session.awaitingDraft=true;}session.playing=false;persist();renderPractice();});}
 catch(error){busy=false;playKind=null;session.playing=false;if(kind==='target'){session.audioOK=false;session.awaitingDraft=true;}persist();renderPractice();notice('Audio could not play. Check your device sound, then start a new phrase. '+error.message);}
}
function saveDraft(){if(!session.awaitingDraft||session.submitted||busy)return;state.updatedAt=Date.now();session.drafts.push({hearing:session.exposures,elapsed:Date.now()-session.created,answer:clone(session.answer)});session.awaitingDraft=false;persist();renderPractice();}
function submit(){if(session.submitted||busy||session.completed===0)return;saveDraft();session.result=grade(session.target,{...session.target,events:session.answer},session.policy.rhythmOnly);session.confidence=$('confidence').value;session.submitted=true;const a=record(!session.audioOK?'invalid audio':session.assistance.length?'assisted':'independent');
 if(independent(a)&&a.result.integrated>=.9&&a.lesson!==null){const id=String(a.lesson),seen=state.lessonPasses[id]??[];if(!seen.includes(a.fingerprint))seen.push(a.fingerprint);state.lessonPasses[id]=seen;}
 const p=progression(state.attempts,a);if(p.action==='advance'&&session.target.level===state.earnedLevel)state.earnedLevel=Math.min(6,state.earnedLevel+1);persist();renderPractice();$('feedback-card').scrollIntoView({block:'start'});if(blockEnd&&Date.now()>=blockEnd)notice('Your planned block is complete. This is a good point for a break. Your progress is saved.');
}
function renderFeedback(){
 const comparison=$('submission-comparison');comparison.replaceChildren();
 for(const [label,id,events,playId] of [['Your answer','submitted-answer',session.answer,'play-answer'],['Correct answer','correct-answer',session.target.events,'hear']]){
  const section=document.createElement('section');section.className='answer-comparison';section.id=id;const heading=document.createElement('h3');heading.textContent=label;section.append(heading);
  if(events.length){const paper=document.createElement('div');paper.className='paper-scroll';paper.innerHTML=staffSVG({...session.target,events},{readonly:true,grid:true,title:label});section.append(paper);}else{const empty=document.createElement('p');empty.textContent=session.result?'No notes were entered.':'Your answer is on paper; no digital transcription was entered.';section.append(empty);}
  const button=document.createElement('button');button.textContent=label==='Your answer'?'Listen to your answer':'Listen to correct answer';button.disabled=busy||!events.length;button.addEventListener('click',()=>$(playId).click());section.append(button);comparison.append(section);
 }
 const r=session.result;$('scores').innerHTML='';$('feedback').replaceChildren();if(!r){$('feedback-title').textContent='Paper self-check';$('feedback').textContent='Your handwriting has not been graded. Compare attacks, durations, rests and pitch landmarks against the target. This self-check cannot establish independent mastery.';$('adaptation').textContent='';return;}
 $('feedback-title').textContent='Your listening evidence.';for(const [title,value] of [['Attack timing',r.attacks],['Durations / rests',r.durations],['Pitch sequence',r.pitch],['Barline grouping',r.notation],['Integrated',r.integrated]]){const card=document.createElement('div');card.className='score-card';const strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=pct(value);span.textContent=title;card.append(strong,span);$('scores').append(card);}
 const ul=document.createElement('ul');for(const msg of [...r.feedback,...r.issues]){const li=document.createElement('li');li.textContent=msg;ul.append(li);}$('feedback').append(ul);
 const rec=state.attempts.find(a=>a.id===session.id),p=rec?progression(state.attempts,rec):{count:0,action:'consolidate'};$('adaptation').textContent=`${rec?.kind??'saved'} evidence. ${p.count} comparable unfamiliar independent items. Recommendation: ${p.action}. Advance after two blocks of eight with at least seven passes per block and every assessed listening component at least 90%.`;
}
function lessonScore(){const l=LESSONS[state.lesson];const score=sequence(l.durations,l.steps,{level:l.level,key:l.key||'C major',meter:l.meter||'4/4',...(l.grouping?{grouping:l.grouping}:{}),instrument:'piano',reference:'pitch'});score.events.forEach(e=>{if(!e.rest)e.acc=keyAcc(score,e.step);});return score;}
function renderLesson(){const l=LESSONS[state.lesson];$('lesson-select').value=state.lesson;$('lesson-title').textContent=l.title;$('lesson-copy').textContent=l.text;$('lesson-score').innerHTML=staffSVG(lessonScore(),{readonly:true,grid:true,title:'Worked example'});const count=(state.lessonPasses[String(state.lesson)]??[]).length;$('lesson-status').textContent=state.lesson===0?'Ungraded tutorial: add a note, then use Undo. The Next lesson button unlocks after those actions.':`${count} unfamiliar independent checks passed. Two checks at 90% on each assessed component unlock Next lesson. You can browse topics without claiming mastery.`;$('lesson-next').disabled=state.lesson===0?!state.tutorialDone:count<2;}
function renderProgress(){renderEvidence();const rows=state.attempts,ind=rows.filter(independent);$('progress-summary').textContent=`${rows.length} saved attempts; ${ind.length} complete independent attempts. Confirmed path: ${LEVELS[state.earnedLevel]}. Assisted work, self-checks and abandoned attempts remain separate. Retention labels require successful unfamiliar retrieval after the scheduled delays.`;$('history').replaceChildren();for(const a of rows.slice(-30).reverse()){const tr=document.createElement('tr');for(const v of [new Date(a.created).toLocaleDateString(),LEVELS[a.target.level],a.kind,a.result?pct(Math.min(a.result.attacks,a.result.durations)):'Not graded',a.result?pct(a.result.pitch):'Not graded',a.exposures]){const td=document.createElement('td');td.textContent=v;tr.append(td);}const td=document.createElement('td'),button=document.createElement('button');button.textContent='Inspect';button.addEventListener('click',()=>inspectAttempt(a));td.append(button);tr.append(td);$('history').append(tr);}}
function renderSettings(){player.volume=state.profile.volume??.7;$('volume').value=Math.round(player.volume*100);$('volume-value').textContent=$('volume').value+'%';$('vocal-rest').checked=state.profile.vocalRest;$('theme').value=state.profile.theme;$('recovery').hidden=!recovery;}
function printSheet(key=false){if(key&&!session.submitted)return;const container=$('print-sheet');container.replaceChildren();const h=document.createElement('h1');h.textContent=key?'Theory Dictation Master: answer key':'Theory Dictation Master: blank worksheet';const p=document.createElement('p');p.textContent=`ID ${session.id.slice(0,8)} · ${session.target.key||'C major'} · ${session.target.meter} [${meterInfo(session.target).grouping}] · ${session.target.bars} bar(s) · ${tempoLabel(session.target)} = ${session.target.bpm} · ${session.policy.hearings} hearings`;container.append(h,p);if(key){const score=document.createElement('div');score.innerHTML=staffSVG(session.target,{readonly:true,title:'Answer key'});container.append(score);}else{const instr=document.createElement('p');instr.textContent='Keep all counts silent. Capture rhythm and pitch landmarks; mark uncertainty and keep following the phrase.';container.append(instr);for(let i=0;i<5;i++){const staff=document.createElement('div');staff.className='blank-staff';container.append(staff);}}window.print();}
function renderEvidence(){
 const target=$('comparisons');target.replaceChildren();
 for(const c of comparisons(state.attempts)){const p=document.createElement('p'),t=c.source.target;p.textContent=`${LEVELS[t.level]} · ${t.key||'C major'} · ${t.meter} [${meterInfo(t).grouping}] · ${t.bpm} BPM · ${t.instrument||'piano'} · ${c.source.policy.support} · ${t.reference||'none'} reference · ${c.source.policy.hearings} hearings: ${c.count} comparable unfamiliar items. `+(c.baseline?`First four vs latest four: rhythm ${pct(c.baseline.rhythm)} → ${pct(c.recent.rhythm)}; pitch ${c.source.policy.rhythmOnly?'not assessed':pct(c.baseline.pitch)+' → '+pct(c.recent.pitch)}; integrated ${pct(c.baseline.integrated)} → ${pct(c.recent.integrated)}.`:'Eight items are needed for a non-overlapping four-versus-four comparison.');target.append(p);}
 if(!target.childNodes.length)target.textContent='Your first independent attempts will appear here. No sample data is included.';
 const list=$('review-list');list.replaceChildren();for(const r of reviewPlan(state.attempts)){const p=document.createElement('p');p.textContent=`${LEVELS[r.source.target.level]} · ${r.source.target.key||'C major'} · ${r.source.target.meter} [${meterInfo(r.source.target).grouping}]: ${r.status}. ${r.isDue?'Review due':'Next review '+new Date(r.due).toLocaleString()}. ${r.count} unfamiliar items.`;list.append(p);}if(!list.childNodes.length)list.textContent='Complete an independent attempt to start a review schedule.';
}
function inspectAttempt(a){
 if(!session.submitted&&session.exposures)assist('history inspected during attempt');
 const box=$('attempt-detail');box.hidden=false;box.replaceChildren();const title=document.createElement('h2');title.textContent='Saved attempt '+a.id.slice(0,8);box.append(title);
 const context=document.createElement('p');context.textContent=`${new Date(a.created).toLocaleString()} · ${a.kind} · Confidence: ${a.confidence||'not recorded'} · ${a.assistance.join(', ')||'No extra aids'}`;box.append(context);
 for(const d of draftEvidence(a)){const p=document.createElement('p');p.textContent=`Hearing ${d.hearing}: rhythm ${pct(Math.min(d.result.attacks,d.result.durations))}, pitch ${pct(d.result.pitch)}, integrated ${pct(d.result.integrated)}. Draft saved ${Math.round(d.elapsed/1000)} seconds after starting the attempt.`;box.append(p);}
 for(const [label,events] of [['Final answer',a.answer],['Target',a.target.events]]){const div=document.createElement('div');div.className='paper-scroll';div.innerHTML=staffSVG({...a.target,events},{readonly:true,title:label});box.append(div);}box.scrollIntoView({block:'start'});
}
function restoreState(next){
 stop();recovery=JSON.stringify(state);localStorage.setItem(KEY+'.recovery',recovery);state=validateBackup(next);session=state.session;targetView=false;paperEntry=false;selected=-1;undo=[];redo=[];
 if(session?.playing){session.playing=false;session.awaitingDraft=true;session.assistance.push('restored interrupted playback');}
 if(!session)newSession();applySetup();player.volume=state.profile.volume??.7;document.body.classList.toggle('light',state.profile.theme==='light');persist();navigate('settings');notice('Previous save restored. Your pre-restore copy is available as a recovery download.');
}
// No entry/edit handler calls Player, Web Audio, speech, or note audition.
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.page)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.go)));document.querySelector('.brand').addEventListener('click',e=>{e.preventDefault();navigate('today');});
for(const [i,title] of LEVELS.entries())$('level').add(new Option(title,String(i)));for(const [title,d] of DURATIONS)$('duration').add(new Option(title,d===null?'unknown':String(d)));$('duration').value='12';for(const [i,l] of LESSONS.entries())$('lesson-select').add(new Option(`${i}. ${l.title}`,String(i)));
on('next','click',()=>newSession());on('hear','click',()=>{if(!session.submitted&&(session.awaitingDraft||session.exposures>=session.policy.hearings))return;return play(session.target,session.policy.support,session.submitted?'debrief':'target');});on('stop','click',stop);on('submit','click',submit);on('save-draft','click',saveDraft);
on('tonic','click',()=>{assist('extra tonic reference');const score=sequence([12],[keyInfo(session.target).tonic],{key:session.target.key||'C major',instrument:session.target.instrument||'piano',reference:'none'});score.events[0].acc=keyAcc(score,score.events[0].step);return play(score,'none','reference');});on('depitch','click',()=>{if(session.policy.mode!=='practice'&&!session.submitted)return;assist('one-pitch reveal');const target=clone(session.target);target.events=target.events.map(e=>e.rest?e:{...e,step:keyInfo(target).tonic,acc:keyAcc(target,keyInfo(target).tonic)});return play(target,'beat','aid');});on('play-answer','click',()=>{if(session.policy.mode!=='practice'&&!session.submitted)return;assist('answer playback');return play({...session.target,events:session.answer},'countin','aid');});
document.querySelectorAll('[data-pitch]').forEach(b=>b.addEventListener('click',()=>add(+b.dataset.pitch)));
on('pitch-up','click',()=>edit({step:Math.min(49,(session.answer[selected]?.step??28)+1),rest:false}));on('pitch-down','click',()=>edit({step:Math.max(21,(session.answer[selected]?.step??28)-1),rest:false}));
on('apply','click',()=>{const c=chosen();if(c.duration!==null&&!Number.isInteger(c.duration))throw Error('Dotted sixteenths are not available yet.');const change={duration:c.duration,acc:c.acc??keyAcc(session.target,session.answer[selected]?.step??28),rest:c.rest};if(c.unknown||c.rest)change.step=null;edit(change);});on('tie','click',()=>edit({tie:!session.answer[selected]?.tie}));on('insert','click',()=>{insert=!insert;showStaff();});on('delete','click',remove);on('undo','click',doUndo);on('redo','click',doRedo);on('grid','change',showStaff);
on('answer-tab','click',()=>{targetView=false;showStaff();});on('target-tab','click',()=>{if(session.submitted||session.assistance.includes('worked example')){targetView=true;showStaff();}});
let pointer=null;
on('score','pointerdown',e=>{if(session.submitted||targetView||busy)return;const note=e.target.closest('[data-note]');pointer={x:e.clientX,y:e.clientY,index:note?+note.dataset.note:-1};});
on('score','pointerup',e=>{if(!pointer||session.submitted||targetView||busy)return;const p=pointer;pointer=null;const svg=$('score').querySelector('svg'),rect=svg.getBoundingClientRect(),y=(e.clientY-rect.top)*300/rect.height;
 if(p.index>=0){selected=p.index;if(Math.abs(e.clientY-p.y)>9&&Math.abs(e.clientX-p.x)<20)edit({step:stepFor(y),rest:false});else showStaff();}
 else if(Math.hypot(e.clientX-p.x,e.clientY-p.y)<9&&y>85&&y<245&&e.clientX-rect.left>105)add(stepFor(y));
});on('score','pointercancel',()=>pointer=null);
on('score','keydown',e=>{if(session.submitted||targetView)return;const k=e.key;if((e.ctrlKey||e.metaKey)&&k.toLowerCase()==='z'){e.preventDefault();e.shiftKey?doRedo():doUndo();return;}if((e.ctrlKey||e.metaKey)&&k.toLowerCase()==='y'){e.preventDefault();doRedo();return;}if(e.ctrlKey||e.metaKey||e.altKey)return;if(/^[a-g]$/i.test(k)){e.preventDefault();add(28+'CDEFGAB'.indexOf(k.toUpperCase()));}else if(k===' '){e.preventDefault();add(28);}else if(k==='Delete'||k==='Backspace'){e.preventDefault();remove();}else if(k==='ArrowUp'||k==='ArrowDown'){e.preventDefault();edit({step:Math.max(21,Math.min(49,(session.answer[selected]?.step??28)+(k==='ArrowUp'?1:-1))),rest:false});}else if(k==='ArrowLeft'||k==='ArrowRight'){e.preventDefault();selected=Math.max(0,Math.min(session.answer.length-1,selected+(k==='ArrowLeft'?-1:1)));showStaff();}else if(k.toLowerCase()==='t')edit({tie:!session.answer[selected]?.tie});});
on('enter-paper','click',()=>{paperEntry=true;showStaff();});on('self-check','click',()=>{if(session.submitted)return;stop();assist('paper self-check reveal');session.submitted=true;session.result=null;record('paper self-check');targetView=true;persist();renderPractice();});
on('export-wav','click',async()=>{assist('external audio export; exposures unobserved');download(await wav(session.target,session.policy.support),session.id.slice(0,8)+'.wav');});on('print-blank','click',()=>printSheet());on('print-key','click',()=>printSheet(true));
on('easier','click',()=>{$('level').value=Math.max(0,session.target.level-1);newSession();notice('Exploratory practice. Confirmed progression still requires independent evidence.');});on('stay','click',()=>{applySetup();newSession();});on('challenge','click',()=>{$('level').value=Math.min(6,session.target.level+1);newSession();notice('Exploratory challenge. The calendar does not promote your confirmed level.');});
on('targeted','click',()=>{if(!session.submitted)return;const old=clone(session.target);if(session.result&&Math.min(session.result.attacks,session.result.durations)<.9){old.events=old.events.map((e,i)=>e.rest?e:{...e,step:keyInfo(old).tonic+i%3,acc:keyAcc(old,keyInfo(old).tonic+i%3)});applySetup();newSession(old,['matched rhythm follow-up']);notice('Same rhythm, new pitches. This is assisted practice. Choose Next phrase afterward for unfamiliar transfer.');}else{applySetup();newSession();}});
on('lesson-select','change',()=>{stop();state.lesson=+$('lesson-select').value;renderLesson();persist();});on('lesson-play','click',()=>play(lessonScore(),'beat','lesson'));on('lesson-guided','click',()=>{const index=state.lesson;stop();$('mode').value='practice';newSession(lessonScore(),['worked example'],index);navigate('practice');notice('Guided example. The target tab is available; this cannot earn independent mastery.');});on('lesson-check','click',()=>{const index=state.lesson;$('level').value=LESSONS[index].level;$('key').value=LESSONS[index].key||'C major';$('meter').value=LESSONS[index].meter||'4/4';$('grouping').value=LESSONS[index].grouping||'';$('mode').value='practice';newSession(null,[],index);navigate('practice');});on('lesson-next','click',()=>{if(state.lesson===0?!state.tutorialDone:(state.lessonPasses[String(state.lesson)]??[]).length<2)return;state.lesson=Math.min(LESSONS.length-1,state.lesson+1);renderLesson();persist();});
on('start-block','click',()=>{blockEnd=Date.now()+(+$('block-length').value)*60000;navigate('practice');notice('Your focused block has started. You can stop early without losing your work.');});
on('vocal-rest','change',()=>{state.updatedAt=Date.now();state.profile.vocalRest=$('vocal-rest').checked;persist();});on('theme','change',()=>{state.updatedAt=Date.now();state.profile.theme=$('theme').value;document.body.classList.toggle('light',state.profile.theme==='light');persist();});
on('export-backup','click',()=>{persist();download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'TheoryDictationMaster-progress.json');});
on('import-backup','change',async e=>{const f=e.target.files[0];if(!f)return;if(f.size>4000000)throw Error('Choose a web backup smaller than 4 MB.');const next=mergeBackup(state,JSON.parse(await f.text()));stop();recovery=JSON.stringify(state);try{localStorage.setItem(KEY+'.recovery',recovery);}catch{}state=next;session=state.session;targetView=false;paperEntry=false;if(session?.playing){session.playing=false;session.awaitingDraft=true;session.assistance.push('interrupted during device transfer');}if(!session)newSession();applySetup();selected=-1;undo=[];redo=[];document.body.classList.toggle('light',state.profile.theme==='light');persist();renderSettings();notice('Progress imported. History was merged and the imported draft is ready in Practice. A pre-import recovery copy is available.');e.target.value='';});
on('recovery','click',()=>download(new Blob([recovery],{type:'application/json'}),'TheoryDictationMaster-recovery.json'));
on('sync-now','click',async()=>{
 stop();persist();$('main').inert=true;$('sync-now').disabled=true;$('sync-status').textContent='Merging progress with your private repository…';
 try{const next=await syncProgress(state,{repo:$('sync-repo').value.trim(),token:$('sync-token').value});
 recovery=JSON.stringify(state);localStorage.setItem(KEY+'.recovery',recovery);state=next;session=state.session;targetView=false;paperEntry=false;selected=-1;undo=[];redo=[];
 if(session?.playing){session.playing=false;session.awaitingDraft=true;session.assistance.push('interrupted during device transfer');}
 if(!session)newSession();applySetup();document.body.classList.toggle('light',state.profile.theme==='light');persist();renderSettings();$('sync-status').textContent='Synced successfully at '+new Date().toLocaleTimeString()+'. Sync on your other device to continue.';
 }catch(e){$('sync-status').textContent=e.message;throw e;}finally{$('main').inert=false;$('sync-now').disabled=false;}
});
on('disconnect-sync','click',()=>{$('sync-token').value='';$('sync-status').textContent='Disconnected. The token was removed from this page.';});
on('reset-progress','click',()=>{
 if(!confirm('Reset all attempts, lessons and drafts in this browser? Sync afterward to apply the reset to your other devices.'))return;
 stop();state={...fresh(),resetAt:Date.now()};session=null;targetView=false;paperEntry=false;selected=-1;undo=[];redo=[];recovery=null;localStorage.removeItem(KEY+'.recovery');localStorage.removeItem(KEY+'.previous');for(const [id,value] of Object.entries({level:'0',bpm:'80',bars:'1',mode:'practice',support:'beat',hearings:'4',duration:'12',accidental:'key',key:'C major',meter:'4/4',grouping:'',instrument:'piano',reference:'pitch'}))$(id).value=value;for(const id of ['rhythm-only','dot','rest','unknown'])$(id).checked=false;document.body.classList.remove('light');newSession();renderSettings();notice('Progress reset. You are starting fresh. Sync now to reset your cloud copy too.');
});
on('start-review','click',()=>{const review=reviewPlan(state.attempts)[0];if(!review)return;const old=session;session=review.source;applySetup();$('instrument').value=session.target.instrument||'piano';session=old;newSession();session.reviewOf=review.source.id;persist();navigate('practice');notice(review.reason+' This is a new phrase under the same conditions.');});
on('volume','input',()=>{player.volume=+$('volume').value/100;state.profile.volume=player.volume;state.updatedAt=Date.now();$('volume-value').textContent=$('volume').value+'%';persist();});
on('save-preset','click',()=>{state.profile.preset=settingValues();state.updatedAt=Date.now();persist();notice('Current next-phrase settings saved.');});
on('load-preset','click',()=>{const preset=state.profile.preset;if(!preset)throw Error('Save practice settings first.');$('grouping').value='';for(const [key,value] of Object.entries(preset)){if(key==='policy')continue;if($(key))$(key).value=value;}for(const [key,value] of Object.entries(preset.policy||{})){if(key==='rhythmOnly')$('rhythm-only').checked=value;else if($(key))$(key).value=value;}newSession();navigate('practice');});
on('restore-previous','click',()=>{const raw=localStorage.getItem(KEY+'.previous');if(!raw)throw Error('No previous save is available.');const next=validateBackup(JSON.parse(raw));if(confirm('Restore the previous local save? A recovery copy of the current state will be kept.'))restoreState(next);});
on('reload-progress','click',()=>location.reload());
window.addEventListener('storage',e=>{if(e.key!==KEY||!e.newValue)return;staleTab=true;player.stop();busy=false;$('tab-conflict').hidden=false;document.querySelectorAll('.page').forEach(p=>p.inert=true);});
let waitingWorker=null;
on('apply-update','click',()=>{stop();persist();waitingWorker?.postMessage({type:'ACTIVATE'});});
window.addEventListener('pagehide',()=>{if(!staleTab){stop();persist();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&busy)stop();});player.onInterrupt=()=>{stop();notice('Playback was interrupted. The hearing is marked assisted; your notation is saved.');};
window.addEventListener('error',e=>notice('Something went wrong: '+e.message));window.addEventListener('unhandledrejection',e=>notice('Something went wrong: '+(e.reason?.message??e.reason)));
session=state.session;if(session){if(session.playing){session.playing=false;session.awaitingDraft=true;session.assistance.push('interrupted by page close');}applySetup();}else{const previousUpdate=state.updatedAt||0;$('level').value=state.earnedLevel;newSession();state.updatedAt=previousUpdate;persist();}
try{recovery=recovery||localStorage.getItem(KEY+'.recovery');}catch{}
player.volume=state.profile.volume??.7;document.body.classList.toggle('light',state.profile.theme==='light');navigate(location.hash.slice(1)||'today');
if('serviceWorker'in navigator){
 let updating=false;navigator.serviceWorker.addEventListener('controllerchange',()=>{if(waitingWorker&&!updating){updating=true;location.reload();}});
 navigator.serviceWorker.register('./sw.js').then(reg=>{
  const offer=()=>{if(reg.waiting&&navigator.serviceWorker.controller){waitingWorker=reg.waiting;$('update-banner').hidden=false;}};offer();reg.addEventListener('updatefound',()=>{reg.installing?.addEventListener('statechange',offer);});
  navigator.serviceWorker.ready.then(()=>$('offline-status').textContent='The app and piano samples are cached for offline use.');
 }).catch(()=>$('offline-status').textContent='Offline caching is unavailable. Use the site online.');
}
