import {LESSONS} from './lessons.js';
import {VERSION,clone,validateScore,grade,fingerprint} from './domain.js';
export const KEY='theory-dictation-master.web.v1';
export const fresh=()=>({schema:1,version:VERSION,profile:{vocalRest:true,theme:'dark'},earnedLevel:0,lesson:0,lessonPasses:{},tutorialDone:false,attempts:[],session:null});
export function validateBackup(input){
 const data=clone(input);
 if(!data||data.schema!==1||!Array.isArray(data.attempts)||data.attempts.length>2000||!Number.isInteger(data.earnedLevel)||data.earnedLevel<0||data.earnedLevel>6||!data.profile||(data.profile.volume!==undefined&&(!Number.isFinite(data.profile.volume)||data.profile.volume<0||data.profile.volume>1))||typeof data.profile.vocalRest!=='boolean'||!['dark','light'].includes(data.profile.theme)||!Number.isInteger(data.lesson)||data.lesson<0||data.lesson>=LESSONS.length||!data.lessonPasses||typeof data.lessonPasses!=='object')throw Error('This is not a valid Theory Dictation Master web backup.');
 if(data.updatedAt!==undefined&&(!Number.isFinite(data.updatedAt)||data.updatedAt<0))throw Error('Invalid update time.');if(data.resetAt!==undefined&&(!Number.isFinite(data.resetAt)||data.resetAt<0))throw Error('Invalid reset time.');for(const [key,values] of Object.entries(data.lessonPasses))if((!/^(0|[1-9][0-9]*)$/.test(key)||+key>=LESSONS.length)||!Array.isArray(values)||values.length>2000||values.some(v=>typeof v!=='string'))throw Error('Invalid lesson evidence.');
 if(data.profile.preset){const p=data.profile.preset;validateScore({meter:p.meter,grouping:p.grouping,key:p.key,level:p.level,bpm:p.bpm,bars:p.bars,events:[]});if(!p.policy||!['practice','exam','paper'].includes(p.policy.mode)||!['beat','subdivision','dropout','countin','none'].includes(p.policy.support)||!Number.isInteger(p.policy.hearings)||p.policy.hearings<1||p.policy.hearings>20||!['piano','flute','clarinet','mixed'].includes(p.instrument)||!['pitch','chord','first','none'].includes(p.reference))throw Error('Invalid saved settings.');}
 const check=s=>{if(!s||typeof s.id!=='string'||s.id.length>100||!Array.isArray(s.answer)||!Array.isArray(s.drafts)||s.drafts.length>20||!Array.isArray(s.assistance)||s.assistance.some(x=>typeof x!=='string'||x.length>150)||!s.policy||!['practice','exam','paper'].includes(s.policy.mode)||!['beat','subdivision','dropout','countin','none'].includes(s.policy.support)||!Number.isInteger(s.policy.hearings)||s.policy.hearings<1||s.policy.hearings>20||!Number.isInteger(s.exposures)||s.exposures<0||s.exposures>1000||!Number.isInteger(s.completed)||s.completed<0||typeof s.audioOK!=='boolean'||typeof s.submitted!=='boolean'||!Number.isFinite(s.created))throw Error('Invalid session record.');validateScore(s.target);validateScore({...s.target,events:s.answer});for(const d of s.drafts)validateScore({...s.target,events:d.answer});};
 for(const a of data.attempts){check(a);if(a.result)a.result=grade(a.target,{...a.target,events:a.answer},a.policy.rhythmOnly);a.fingerprint=fingerprint(a.target);}if(data.session){check(data.session);if(data.session.result)data.session.result=grade(data.session.target,{...data.session.target,events:data.session.answer},data.session.policy.rhythmOnly);}
 return clone(data);
}
export function read(storage){const raw=storage.getItem(KEY);return raw?validateBackup(JSON.parse(raw)):fresh();}
export function save(storage,data){if(data.attempts.length>2000)throw Error('History is full. Export a backup before resetting progress.');const serialized=JSON.stringify(data);const previous=storage.getItem(KEY);if(previous&&previous!==serialized)storage.setItem(KEY+'.previous',previous);storage.setItem(KEY,serialized);}
export function mergeBackup(current,incoming){
 const other=validateBackup(incoming),map=new Map(current.attempts.map(a=>[a.id,a]));for(const a of other.attempts)if(!map.has(a.id))map.set(a.id,{...a,kind:'imported'});
 // Imported evidence stays visible but never silently manufactures mastery in this browser.
 if(other.session&&!other.session.submitted&&!other.session.assistance.includes('imported draft'))other.session.assistance.push('imported draft');
 return {...current,session:other.session,attempts:[...map.values()].sort((a,b)=>a.created-b.created),lesson:other.lesson,profile:other.profile};
}
